version: "3"

services:
  wtwt-front-end:
    build: './wtwt-frontend'
    container_name: what-to-watch-tonight_frontend
    image: what-to-watch-tonight_frontend
    working_dir: /app
    env_file:
      - ./wtwt-frontend/docker.env
    expose:
      - 3000
    ports:
      - 80:3000
    networks:
      - wtwt

  wtwt-back-end:
      build: './wtwt-backend'
      container_name: what-to-watch-tonight_backend
      image: what-to-watch-tonight_backend
      working_dir: /app
      env_file:
      - ./wtwt-backend/docker.env
      expose:
      - 5000
      ports:
      - 5000:5000
      networks:
      - wtwt
  wtwt-ML:
    build: './wtwt-ml-model'
    container_name: what-to-watch-app
    working_dir: /app
    ports:
      - "${PORT:-5050}:${PORT:-5050}"
    env_file:
      - ./wtwt-ml-model/docker.env
    networks:
      - wtwt

networks:
    wtwt:
        name: wtwt
        driver: bridge
