services:
  wtwt-front-end:
    build:
      context: './wtwt-front-end'
    container_name: what-to-watch-tonight_frontend
    image: what-to-watch-tonight-frontend
    working_dir: /app
    expose:
      - 3000
    ports:
      - "80:3000"
    networks:
      - wtwt

  wtwt-back-end:
    build: './wtwt-back-end'
    container_name: what-to-watch-tonight_backend
    image: what-to-watch-tonight-backend
    working_dir: /app
    env_file:
      - ./envs/.env.back-end
    expose:
      - 5000
    ports:
      - "5000:5000"
    networks:
      - wtwt

  wtwt-ml-model:
    build: './wtwt-ml-model'
    container_name: what-to-watch-ml-model
    image: what-to-watch-tonight-ml-model
    working_dir: /app
    env_file:
      - ./envs/.env.python
    expose:
      - 5050
    networks:
      - wtwt

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686"  # Jaeger UI
      - "14268"
      - "14250"
    networks:
      - wtwt

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # http gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
    links:
      - jaeger
    networks:
      - wtwt

networks:
  wtwt:
    name: wtwt
    driver: bridge