services:
  wtwt-front-end:
    build: './wtwt-front-end'
    container_name: what-to-watch-tonight_frontend
    image: what-to-watch-tonight-frontend
    working_dir: /app
    # env_file:
    #   - ./envs/front-end.env
    expose:
      - 3000
    ports:
      - 80:3000
    networks:
      - wtwt

  wtwt-back-end:
    build: './wtwt-back-end'
    container_name: what-to-watch-tonight_backend
    image: what-to-watch-tonight-backend
    working_dir: /app
    env_file:
      - ./envs/back-end.env
    expose:
      - 5000
    networks:
      - wtwt

  wtwt-ml-model:
    build: './wtwt-ml-model'
    container_name: what-to-watch-ml-model
    image: what-to-watch-tonight-ml-model
    working_dir: /app
    env_file:
      - ./envs/ml.env
    expose:
      - 5050
    networks:
      - wtwt

networks:
  wtwt:
    name: wtwt
    driver: bridge