@startuml
actor User

participant "Front-end (Next.js)" as FrontEnd
participant "BFF (Node.js)" as BFF
participant "Machine Learning Service (Python)" as MLService
participant "TMDB API" as TMDB

User -> FrontEnd: Accesses the application
FrontEnd -> User: Displays questions about mood, preferences, and release year
User -> FrontEnd: Answers the questions
FrontEnd -> BFF: Sends answers (HTTP GET /movie)
BFF -> MLService: Requests movie recommendation (HTTP POST /movie)
MLService -> BFF: Returns recommended movies
BFF -> TMDB: Requests additional movie information (HTTP GET /movie/{...params})
TMDB -> BFF: Returns movie information
BFF -> FrontEnd: Returns recommended movie with additional information
FrontEnd -> User: Displays recommended movie and an array of other suggestions

User -> FrontEnd: Requests more recommendations
FrontEnd -> BFF: Requests more recommendations with the array of suggestions (HTTP GET /more-recommendations)

loop Polling for additional movie information
    BFF -> TMDB: Requests additional movie details (HTTP GET /movie/{...params})
    TMDB -> BFF: Returns movie details
end

BFF -> FrontEnd: Returns more recommended movies with additional information
FrontEnd -> User: Displays more recommended movies

@enduml
